<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_warningLastName</name>
   <tag></tag>
   <elementGuidId>07949320-1a68-4781-a668-12bc409a070e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lastname-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='lastname-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a54c3fbe-926b-444d-a61b-6fef5aae135b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>lastname</value>
      <webElementGuid>2989aeae-95b0-40b2-a230-1059a099e7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>generated</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0ee5e0a0-e6d9-4c21-8419-7c80f9360cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mage-error</value>
      <webElementGuid>e2509b4f-3f62-4ab4-8894-e7577358396e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lastname-error</value>
      <webElementGuid>d9a8adb9-e37c-42ce-904e-ca25b03e4c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This is a required field.</value>
      <webElementGuid>c97f9ae2-0b83-4ba1-97df-993537ca5285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lastname-error&quot;)</value>
      <webElementGuid>62349eb0-62be-4583-b8c2-86abf3f079e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='lastname-error']</value>
      <webElementGuid>9fb9b31c-f846-444e-ae9d-b08f304b05d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-validate']/fieldset/div[2]/div/div</value>
      <webElementGuid>ce15fd9b-70b6-4dbe-8cd8-6c32adb13d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/following::div[2]</value>
      <webElementGuid>dbe41cc8-1840-478c-85fb-eaea9c586154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is a required field.'])[1]/following::div[3]</value>
      <webElementGuid>3e3e9ac4-c312-44e7-936c-e2a5d76d4a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up for Newsletter'])[1]/preceding::div[1]</value>
      <webElementGuid>32aca004-52ba-4954-9d8e-7bc3a2308047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign-in Information'])[1]/preceding::div[2]</value>
      <webElementGuid>d6b25722-a653-4033-8d21-1428afffb934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div/div</value>
      <webElementGuid>5f16651a-798a-4a91-870f-32da5d309737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'lastname-error' and (text() = 'This is a required field.' or . = 'This is a required field.')]</value>
      <webElementGuid>72be4266-5f20-48b9-a970-b6312eba7316</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
